---
- name: Playbook to create a basic jekyll site
  hosts: localhost 
  connection: local
  gather_facts: true 
  tasks:
    - name: Create Jekyll Group
      clc_group:
        location: 'UC1'
        name: 'Jekyll-demo'
        state: present
      register: clc_grp

    - debug: var=clc_grp

    - name: Create Jekyll Server
      clc_server:
        name: jekyll
        template: ubuntu-14-64
        location: 'UC1'
        group: 'Jekyll-demo'
        count: 1
        password: abc123!$#
      register: clc_svr

    - debug: var=clc_svr

    - pause:
        minutes: 1

    - name: Add the new server to the inventory
      add_host: name={{clc_svr.servers[0].name}}  groups=jekyll_group ansible_ssh_pass=abc123!$# ansible_connection=ssh ansible_ssh_host={{clc_svr.servers[0].ipaddress}} ansible_ssh_user=root ansible_host_key_checking=false
      

- hosts: jekyll_group
  gather_facts: false 
  tasks:

    - name: Refresh apt Cache
      apt: update_cache=yes
 
    - name: Install make
      apt: name=make state=present 
 
    - name: Install nodejs
      apt: name=nodejs state=present

    - name: Install ruby
      apt: name=ruby-full state=present 

    - name: Install Jekyll 
      shell: gem install jekyll -v 2.5.3

    - name: Create Blog Directory
      file: path=/data01 state=directory mode=0755
      
    - name: Create the Site
      shell: jekyll new /data01/myBlog 

    - name: Run the Jekyll Service
      shell: jekyll serve --source /data01/myBlog --destination /data01/myBlog/_site --detach --host $(hostname -I) 
